apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-ready-example
spec:
  selector:
    matchLabels:
      app: app-ready-example
  replicas: 1
  template:
    metadata:
      labels:
        app: app-ready-example
    spec:
      containers:
      - name: app-ready-example
        image: ghcr.io/guymenahem/app-no-probes:0.0.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: https
          protocol: TCP
